apiVersion: apps/v1
kind: Deployment
metadata:
 name: cicuitbrakerlab
 labels:
    app: cicuitbrakerlab
spec:
 replicas: 2
 selector:
    matchLabels:
      app: cicuitbrakerlab
 template:
    metadata:
       labels:
        app: cicuitbrakerlab
    spec:
      containers:
      - name: cicuitbrakerlabcontainer
        image: docker.io/jptabja/cicuitbrakerlab:latest
        ports:
        - containerPort: 8080